name: SailPoint Connector CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build connector
        run: npm run build

      - name: Package SailPoint connector
        run: npm run pack-zip
      - name: Upload connector artifact
        uses: actions/upload-artifact@v4
        with:
          name: connector-package
          path: "*.zip"